version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
      - run:
          name: The First Step
          command: gradle test
      - store_test_results:
          path: test-results

  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
      - run: gradle jar
      - store_artifacts:
          path: /code/test-results
          destination: prefix
workflows:
  version: 2
  feature_master:
    jobs:
      - test:
      - package:
          requires:
            - test
          
